### ISSUE TITLE
raw_user_side_information_data.dat

### ISSUE THREAD

**Issue by s1162276945** [daicoolb/ConvMF_V2.0#1]
你好，我想问一下这份原始数据（raw_user_side_information_data.dat）如果方便的话可以发给我一份吗，谢谢了，我的邮箱号：1162276945@qq.com。

**Comment by daicoolb** [comment]
You can generate it by user side information ~~ it is very easy.

**Comment by s1162276945** [comment]
Thank you, but I only have "users.dat", but the second term of each line is not binary type, not the same as yours, since I have see it detail,  thank you.

**Comment by s1162276945** [comment]
Excuse me, but how can I find the file "user side information", in fact, I don't know what is it. There are pieces of your code here:
--------------------------------------------------------------------------------------------------------------
"-b", "--raw_user_side_information_data_path",type=str,  help="Path to raw user side information, side information consists of binary value data format - user_id::binary value..."
--------------------------------------------------------------------------------------------------------------
Also, I am confused of what the "binary value" is, can you do me a favor, my email address is 1162276945@qq.com, thank you very much...

**Comment by s1162276945** [comment]
When I use users.dat to run the code, Error araised
ValueError: Error when checking : expected user_sideinformation to have shape (None, 42) but got array with shape (6040, 4)

**Comment by daicoolb** [comment]
the binary value is like this "01010010101"

**Comment by daicoolb** [comment]
Maybe you didn't define the user_feature in the model so caused the value error

**Comment by s1162276945** [comment]
thank you very much，I try to use users.dat to get user_side_information, and try to encode the attribute into binary value, but failed, I have looked some code from github, but failed to deal with it, so I came to ask you for help,  hope you could help me if possible, thank you.

**Comment by daicoolb** [comment]
I have a variant with ConvMF. so it maybe not used for the old version.  After I finished my paper , I will update this.

**Comment by s1162276945** [comment]
thank you，good luck

**Comment by s1162276945** [comment]
Hello, have you finished your paper now, how I can read your paper, does it published?

**Comment by daicoolb** [comment]
it may need two weeks to know the result. Thanks for your attention.

**Comment by s1162276945** [comment]
oh, can you send me your paper after it reiceived?

**Comment by daicoolb** [comment]
No problem

**Comment by s1162276945** [comment]
Thank you

**Comment by daicoolb** [comment]
@s1162276945 My paper has been accepted. Do you still need to read my paper ?

**Comment by s1162276945** [comment]
Yes, thank you very much, and will  you update the code?

**Comment by s1162276945** [comment]
hello, can I have your contact information?

**Comment by s1162276945** [comment]
hello, thank you remmenber me, I want to know where your paper was accepted by.

**Comment by s1162276945** [comment]
Congratulations to you.

**Comment by daicoolb** [comment]
Here is the new model's url: 
https://github.com/daicoolb/PHDMF

Here is the paper list:
ID#69: PHD: A Probabilistic Model of Hybrid Deep Collaborative Filtering for Recommender Systems
http://www.acml-conf.org/2017/conference/accepted-papers/

**Comment by s1162276945** [comment]
how can I download the paper, there seems no download link.

**Comment by s1162276945** [comment]
I have sent email to ACML, can you upload this paper to github if it is convenient for you.

**Comment by daicoolb** [comment]
you can give me an email. I send it to you.

**Comment by s1162276945** [comment]
1162276945@qq.com

**Comment by s1162276945** [comment]
Thank you very much.

**Comment by s1162276945** [comment]
aha, so kind of you, hope you could deliver more papers the day and future.

**Comment by s1162276945** [comment]
my email address is 1162276945@qq.com

**Comment by s1162276945** [comment]
hey，my friend

**Comment by daicoolb** [comment]
Ok. I have sent it to you~

**Comment by s1162276945** [comment]
thank you again, my friend.
