### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by heyaqiong123** [daicoolb/ConvMF_V2.0#2]
您好，很有幸拜读了您的代码。我想向您请教一下运行环境，我看您的run.py内的语法是类似py2.7，但我采用2.7后，可以进行预处理。但在执行矩阵分解时会报错，缺乏tensorflow.官网上tf的2.7不支持windows，所以想向您参考一下整个程序的运行环境。

**Comment by daicoolb** [comment]
我的环境就是tensorflow python2.7，linux

**Comment by Ming2018ming** [comment]
您好，最近很有幸拜读了您的代码，我用最原始的convmf中的数据集跑了一下，但是不成功，所以想用下您的数据集，如果您有时间，请您尽快回复一下，谢谢！

**Comment by daicoolb** [comment]
@Ming2018ming Sorry, I don't have the  dataset now.

**Comment by Ming2018ming** [comment]
好的，谢谢您，虽然有些遗憾，但还是很感谢您在百忙之中回复信息




------------------ 原始邮件 ------------------
发件人: "Beili"<notifications@github.com>; 
发送时间: 2019年10月11日(星期五) 中午1:41
收件人: "daicoolb/ConvMF_V2.0"<ConvMF_V2.0@noreply.github.com>; 
抄送: "MM@angle"<1091117259@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [daicoolb/ConvMF_V2.0] 运行环境 (#2)




@Ming2018ming Sorry, I don't have the dataset now.
